version: '3'

services:
  redis:
    container_name: "redis"
    image: redis:6-alpine
    ports:
      - "6379:6379"
  api:
    container_name: "runner-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis