version: '3'

services:
  api:
    container_name: "runner-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    networks:
      - ingsis-network
    depends_on:
      - db
      - redis
  db:
    container_name: "runner-db"
    image: postgres:12
#    ports:
#      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - ingsis-network


  redis:
    container_name: "redis"
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - ingsis-network

volumes:
  runner_db:

networks:
  ingsis-network:
    external: true