name: "docker-image.yml"
on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: austral-ingsis
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/austral-ingsis/echo:${{ steps.short-sha.outputs.sha }}
      

      - name: Refresh container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: "tricolor-ingsis"
          key: ${{ secrets.INGSIS_DEV_KEY }}
          script: |
            cd snippet-runner-api
            sudo docker stop snippet-runner-api
            sudo docker compose -f docker-compose.dev.yml up -d snippet-runner-api